/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from "@solana/web3.js";
import * as beet from "@metaplex-foundation/beet";
import * as beetSolana from "@metaplex-foundation/beet-solana";
export type VaultConfig = {
  strategy: web3.PublicKey;
  authority: web3.PublicKey;
  strategist: web3.PublicKey;
  fixedRate: number;
  startAt: beet.bignum;
  investAt: beet.bignum;
  redeemAt: beet.bignum;
};

/**
 * @category userTypes
 * @category generated
 */
export const vaultConfigBeet = new beet.BeetArgsStruct<VaultConfig>(
  [
    ["strategy", beetSolana.publicKey],
    ["authority", beetSolana.publicKey],
    ["strategist", beetSolana.publicKey],
    ["fixedRate", beet.u16],
    ["startAt", beet.u64],
    ["investAt", beet.u64],
    ["redeemAt", beet.u64],
  ],
  "VaultConfig"
);
